environment:
  global:
    CABAL_OPTIONS: "--store-dir=C:\\CABAL_STORE --http-transport=plain-http"
    CABAL_VERSION: "3.2.0.0"
    GNUPGHOME: 'example/gnupg'  # This shouldn't work
  matrix:
    - GHC_VERSION: "8.8.3"
    - GHC_VERSION: "8.6.5"
    - GHC_VERSION: "8.4.4"
    - GHC_VERSION: "8.2.2"
    - GHC_VERSION: "8.0.2"

cache:
  - "C:\\CABAL_STORE"

install:
  # https://help.appveyor.com/discussions/questions/20054-installing-gnupg-for-tests
  - ps: |
          $path = [Environment]::GetEnvironmentVariable("path", "machine")
          $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
  - appveyor-retry choco install -y ghc --version %GHC_VERSION%
  - appveyor-retry choco install -y cabal --version %CABAL_VERSION%
  - appveyor-retry choco install -y gnupg
  - refreshenv
  - gpg --version
  - ghc --version
  - cabal --version
  - cabal %CABAL_OPTIONS% new-update -v

build_script:
  - cabal %CABAL_OPTIONS% new-build all test:tests
