environment:
  global:
    CABAL_OPTIONS: "--store-dir=C:\\CABAL_STORE --http-transport=plain-http"
    GNUPGHOME: 'example/gnupg'  # This shouldn't work
  matrix:
    - GHC_VERSION: "8.10.7"

cache:
  - "C:\\CABAL_STORE"

install:
  # https://help.appveyor.com/discussions/questions/20054-installing-gnupg-for-tests
  - ps: |
          $path = [Environment]::GetEnvironmentVariable("path", "machine")
          $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
  - appveyor-retry choco install -y ghc --version %GHC_VERSION%
  - appveyor-retry choco install -y gnupg
  - refreshenv
  - cabal %CABAL_OPTIONS% v2-update -v

build_script:
  - cabal %CABAL_OPTIONS% v2-build all test:tests
