[package]
name = "ananke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.30", features = ["macros", "formatting", "parsing", "serde"] }

[dev-dependencies]
rand = "0.8.5"
